/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "aws-nextjs",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
    };
  },
  async run() {
    // No `access` argument: the bucket stays private and objects are only
    // reachable through pre-signed URLs generated by the app.
    const bucket = new sst.aws.Bucket("MyBucket", {
      // Required for browser PUT uploads. Origins are open because the
      // security boundary is the short-lived pre-signed URL, not CORS.
      cors: {
        allowMethods: ["PUT", "GET", "HEAD"],
        allowOrigins: ["*"],
        allowHeaders: ["*"],
        exposeHeaders: ["ETag"],
        maxAge: "1 hour",
      },
      // Keep storage costs bounded: uploads are removed after 30 days.
      lifecycle: [
        {
          id: "expire-uploads",
          enabled: true,
          expiresIn: "30 days",
        },
      ],
    });

    new sst.aws.Nextjs("MyWeb", { link: [bucket] });
  },
});
